//let base_path = "http://localhost:80/"
let base_path = "https://dataviziosa.github.io/PotterViz/"
let data_path = base_path + "data/"
let cleaned_path = data_path+ "cleaned/"
let char_images = data_path+"images/characters/"
let ext_img = ".png"
