data_folder = "../data/"
hpcollection_folder = data_folder+"hpcollection/"
hp_network_folder = data_folder+"hp_networks/"
hpbooks_folder = data_folder+"hpbooks/"
movies_folder = data_folder+"movies/"
cleaned_folder = data_folder+"cleaned/"
